# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS)     += sensor_info.o
obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS)		+= HS_SNS_DRV/
