/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2019, The Linux Foundation. All rights reserved.
 */

#define CONFIG_DRM_MSM 1
#define CONFIG_DRM_MSM_SDE 1
#define CONFIG_SYNC_FILE 1
#define CONFIG_DRM_MSM_DSI 1
#define CONFIG_DSI_PARSER 1
#define CONFIG_DRM_MSM_REGISTER_LOGGING 1
#define CONFIG_DRM_SDE_EVTLOG_DEBUG 1
#define CONFIG_QCOM_MDSS_PLL 1
#define CONFIG_MSM_SDE_ROTATOR 1
#define CONFIG_MSM_SDE_ROTATOR_EVTLOG_DEBUG 1
#define CONFIG_HS_EPD_PANEL_SUPPORT 1
#define CONFIG_AW99703_CONTINUOUS_BL 1
#define CONFIG_HISENSE_PRODUCT_DEVINFO 1
#define CONFIG_AW99703_SWAP 1
#define CONFIG_EPD_PWROFF_CHG_BL 1
#define CONFIG_EPD_PWROFF_CHG_READ_FLAG 1
#define CONFIG_EPD_PMIC_INTERGRATED_INTFACE 1